services:
  backend:
    build:
      context: ./backend
    container_name: algorithmlab_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    container_name: algorithmlab_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
