apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algorithmlab-ingress
  namespace: algorithmlab
spec:
  ingressClassName: nginx
  rules:
    - host: algorithmlab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 5173
