name: Kubernetes Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kubernetes-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: >
            -summary
            -strict
            -ignore-missing-schemas
            k8s/
